### ISSUE TITLE
[Task]: Add home screen

### ISSUE THREAD

**Issue by l10es** [l10es/tms#1]
### Task Details

* [x] Create main page of this app
* [x] Add bottom bar to navigate other screen

### Task Goal

* [x] User can show main page when launch the app

**Comment by l10es** [comment]
All task has been completed.
Now allows to create the pull request.
